services:
  backend:
    image: ghcr.io/andreit07/neuraleye_backend:latest
    ports:
      - "8080:8080"
    volumes:
      - ./appsettings.json:/app/appsettings.json
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      neuraleye_network:
        ipv4_address: X.X.X.X
networks:
  neuraleye_network:
    external: true