name: Docker Backend Image CI for GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'

jobs:
  build_and_publish_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.GHCK_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build ./Backend --tag ghcr.io/${{ vars.USERNAME }}/neuraleye_backend:latest
          docker push ghcr.io/${{ vars.USERNAME }}/neuraleye_backend:latest