name: Docker Frontend Image CI for GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/**'

jobs:
  build_and_publish_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.GHCK_TOKEN }}

      - name: Build and push frontend image
        run: |
          docker build ./Frontend --tag ghcr.io/${{ vars.USERNAME }}/img_frontend:latest
          docker push ghcr.io/${{ vars.USERNAME }}/img_frontend:latest