name: Docker Image CI

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and push backend image
        run: |
          echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u andreit07 --password-stdin
          docker build ./Backend --tag ghcr.io/andreit07/img_backend:latest
          docker push ghcr.io/andreit07/img_backend:latest

      - name: Build and push frontend image
        run: |
          docker build .Frontend --tag ghcr.io/andreit07/img_frontend:latest
          docker push ghcr.io/andreit07/img_frontend:latest
